version: '3.8'
services:
  database:
    container_name: byte_database
    image: mongo:latest
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./packages/docker/database:/data/db
  server:
    container_name: byte_server
    build: ./packages/server
    command: yarn start:development
    depends_on:
      - database
    ports:
      - 5050:5050
    volumes:
      - ./packages/server:/server
      - /server/node_modules
  client:
    container_name: byte_client
    build: ./packages/client
    command: >
      sh -c "yarn build &&
             yarn start"
    depends_on:
      - server
    ports:
      - 3000:3000
